//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Reddit32StreamingEntryPointNodePresenter : NSObject
{
    // Error parsing type: , name: accountContext
    // Error parsing type: , name: streamManager
    // Error parsing type: , name: current
    // Error parsing type: , name: delegate
    // Error parsing type: , name: uiVariant
    // Error parsing type: , name: pageType
    // Error parsing type: , name: viewSessionId
    // Error parsing type: , name: playbackTracker
    // Error parsing type: , name: isLive
    // Error parsing type: , name: topStreamsUpdateTimer
    // Error parsing type: , name: heartbeatTimer
    // Error parsing type: , name: heartbeatDelayTimer
    // Error parsing type: , name: streamUpdateTimer
    // Error parsing type: , name: isActive
    // Error parsing type: , name: copyVariant
}

- (void).cxx_destruct;
- (id)init;
- (void)didUpdateStreamingConfig;
- (void)dealloc;
- (id)initWithAccountContext:(id)arg1 streamManager:(id)arg2 delegate:(id)arg3;

@end

