//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASDisplayNode.h>

#import "ASPagerDataSource-Protocol.h"
#import "ASPagerDelegate-Protocol.h"

@interface _TtC6Reddit24FeedPostImageGalleryNode : ASDisplayNode <ASPagerDataSource, ASPagerDelegate>
{
    // Error parsing type: , name: post
    // Error parsing type: , name: feedPostOptions
    // Error parsing type: , name: pagerNode
    // Error parsing type: , name: pages
    // Error parsing type: , name: countTextNode
    // Error parsing type: , name: $__lazy_storage_$_captionNode
    // Error parsing type: , name: $__lazy_storage_$_urlNode
    // Error parsing type: , name: $__lazy_storage_$_linkSymbolNode
    // Error parsing type: , name: pageControlNode
    // Error parsing type: , name: pendingOverlaysVisibility
    // Error parsing type: , name: currentOverlaysVisibility
}

+ (double)captionAndLinkBarHeight;
- (void).cxx_destruct;
- (id)init;
- (void)scrollViewDidScroll:(id)arg1;
- (id)pagerNode:(id)arg1 nodeAtIndex:(long long)arg2;
- (long long)numberOfPagesInPagerNode:(id)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)onURLTapped;
- (void)didEnterVisibleState;
- (void)didLoad;
- (id)initWithPost:(id)arg1 feedPostOptions:(id)arg2 delegate:(id)arg3;

@end

