//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditAssets/_TtC12RedditAssets6Assets.h>

@interface _TtC12RedditAssets6Assets (RedditAssets)
+ (id)dataWithCatalogName:(id)arg1;
+ (id)fileWithName:(id)arg1 extension:(id)arg2;
@end

