//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s12RedditAssets0B0CN.h"

@class _TtCC12RedditAssets6Assets13ImageResource, _TtCC12RedditAssets6Assets20LocalizationResource, _TtCC12RedditAssets6Assets23LottieAnimationResource;

@interface _TtC7Economy10EconAssets : _$s12RedditAssets0B0CN
{
    // Error parsing type: , name: iconCoin20
    // Error parsing type: , name: awardLocked
    // Error parsing type: , name: awardMod
    // Error parsing type: , name: awardNew
    // Error parsing type: , name: awardPremium
    // Error parsing type: , name: bannerCoinMarketing
    // Error parsing type: , name: backgroundCoinBonus
    // Error parsing type: , name: backgroundCoinMarketing
    // Error parsing type: , name: coinLarge
    // Error parsing type: , name: coin
    // Error parsing type: , name: redditCoinWhite
    // Error parsing type: , name: storefrontAwardAvailable
    // Error parsing type: , name: storefrontAwardClaim
    // Error parsing type: , name: marketing
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets20LocalizationResource *marketing; // @synthesize marketing;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets23LottieAnimationResource *storefrontAwardClaim; // @synthesize storefrontAwardClaim;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets23LottieAnimationResource *storefrontAwardAvailable; // @synthesize storefrontAwardAvailable;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *redditCoinWhite; // @synthesize redditCoinWhite;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *coin; // @synthesize coin;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *coinLarge; // @synthesize coinLarge;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *backgroundCoinMarketing; // @synthesize backgroundCoinMarketing;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *backgroundCoinBonus; // @synthesize backgroundCoinBonus;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *bannerCoinMarketing; // @synthesize bannerCoinMarketing;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *awardPremium; // @synthesize awardPremium;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *awardNew; // @synthesize awardNew;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *awardMod; // @synthesize awardMod;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *awardLocked; // @synthesize awardLocked;
@property(nonatomic, readonly) _TtCC12RedditAssets6Assets13ImageResource *iconCoin20; // @synthesize iconCoin20;

@end

