//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASScrollNode.h>

#import <Economy/ObjectObserverProtocol-Protocol.h>

@protocol _TtP7Economy26FeedPostAwardsNodeDelegate_;

@interface _TtC7Economy18FeedPostAwardsNode : ASScrollNode <ObjectObserverProtocol>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: post
    // Error parsing type: , name: accountPk
    // Error parsing type: , name: awardsPlaqueEnabled
    // Error parsing type: , name: shouldAnimateLastGivenAward
    // Error parsing type: , name: awardsNodes
    // Error parsing type: , name: totalAwardsReceivedNode
    // Error parsing type: , name: addAwardNode
}

+ (struct CGSize)calculatedSizeWithData:(id)arg1 accountPk:(id)arg2 maxWidth:(double)arg3;
- (void).cxx_destruct;
- (id)init;
- (void)processAwardingCompleteNotificationWithNotification:(id)arg1;
- (void)updateContentViewsForData:(id)arg1 changeKeyPath:(id)arg2 oldValue:(id)arg3 newValue:(id)arg4;
- (void)didTapAddAwardWithNode:(id)arg1;
- (void)didTapAwardWithNode:(id)arg1;
- (void)didTapAwardsNode;
- (id)layoutSpecThatFits:(CDStruct_34f59b8e)arg1;
- (void)didExitHierarchy;
- (void)didEnterHierarchy;
- (void)didLoad;
- (id)initWithPost:(id)arg1 accountPk:(id)arg2 awardsPlaqueEnabled:(_Bool)arg3;
@property(nonatomic) __weak id <_TtP7Economy26FeedPostAwardsNodeDelegate_> delegate; // @synthesize delegate;

@end

