//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AnalyticsProcessorDelegate-Protocol.h"
#import "_TtP7Economy22EconomyAnalyticsLogger_-Protocol.h"

@class Account, AnalyticsEventProcessor, AppSettings, ExperimentManager, Loid, NSString;

@interface AnalyticsManager : NSObject <_TtP7Economy22EconomyAnalyticsLogger_, AnalyticsProcessorDelegate>
{
    Account *_account;
    Loid *_loid;
    AppSettings *_appSettings;
    AnalyticsEventProcessor *_eventProcessor;
    ExperimentManager *_experimentManager;
}

+ (void)recordTraceWithSentryForAppBackgrounded;
+ (void)recordTraceWithSentryForEvent:(id)arg1;
+ (void)logEvent:(id)arg1 usingAnalyticsManager:(id)arg2;
+ (void)logEvents:(id)arg1 usingAnalyticsManager:(id)arg2;
+ (void)appBackgroundedUsingAnalyticsManager:(id)arg1;
+ (void)setIsEnabled:(_Bool)arg1;
+ (_Bool)isEnabled;
+ (id)instance;
- (void).cxx_destruct;
@property(readonly, nonatomic) ExperimentManager *experimentManager; // @synthesize experimentManager=_experimentManager;
@property(readonly, nonatomic) AnalyticsEventProcessor *eventProcessor; // @synthesize eventProcessor=_eventProcessor;
@property(readonly, nonatomic) AppSettings *appSettings; // @synthesize appSettings=_appSettings;
@property(readonly, nonatomic) Loid *loid; // @synthesize loid=_loid;
@property(readonly, nonatomic) Account *account; // @synthesize account=_account;
- (void)persistInstallTimeStamp;
- (void)appBackgrounded;
- (void)logAnalyticsEvents:(id)arg1;
- (void)logAnalyticsEvent:(id)arg1;
- (void)configureWithBranchParameters:(id)arg1 isFirstLaunch:(_Bool)arg2;
- (_Bool)isProcessingEnabled;
- (id)initWithService:(id)arg1 appSettings:(id)arg2 errorReporter:(id)arg3;
- (void)logLaunchEventWithReferringURL:(id)arg1 isFirstLaunch:(_Bool)arg2;
- (void)logWithEvents:(id)arg1;
- (void)logWithEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

