//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface PostGalleryItem : NSObject
{
    NSString *_caption;
    NSURL *_outboundURL;
    NSString *_mediaId;
    NSString *_userId;
    NSString *_mimeType;
    NSURL *_url;
    struct CGSize _size;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(readonly, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(readonly, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(readonly, nonatomic) NSURL *outboundURL; // @synthesize outboundURL=_outboundURL;
@property(readonly, nonatomic) NSString *caption; // @synthesize caption=_caption;
- (id)initWithData:(id)arg1 mediaMetadata:(id)arg2;
- (id)initWithGraphQLData:(id)arg1;

@end

