//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Media, NSArray, NSString;

@interface TopAwardedPost : NSObject
{
    _Bool _isSpoiler;
    NSArray *_awards;
    unsigned long long _score;
    unsigned long long _rank;
    NSString *_postId;
    unsigned long long _totalAwards;
    NSString *_postTitle;
    NSString *_subredditId;
    NSString *_subredditName;
    Media *_media;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) Media *media; // @synthesize media=_media;
@property(readonly, nonatomic) NSString *subredditName; // @synthesize subredditName=_subredditName;
@property(readonly, nonatomic) NSString *subredditId; // @synthesize subredditId=_subredditId;
@property(readonly, nonatomic) _Bool isSpoiler; // @synthesize isSpoiler=_isSpoiler;
@property(readonly, nonatomic) NSString *postTitle; // @synthesize postTitle=_postTitle;
@property(readonly, nonatomic) unsigned long long totalAwards; // @synthesize totalAwards=_totalAwards;
@property(readonly, nonatomic) NSString *postId; // @synthesize postId=_postId;
@property(readonly, nonatomic) unsigned long long rank; // @synthesize rank=_rank;
@property(readonly, nonatomic) unsigned long long score; // @synthesize score=_score;
@property(readonly, nonatomic) NSArray *awards; // @synthesize awards=_awards;
- (id)initWithData:(id)arg1;

@end

